# Generated by Django 4.1.7 on 2023-04-11 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0002_alter_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='acc_creation_dte',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 4, 11, 23, 29, 32, 548953), null=None),
        ),
    ]
