# Generated by Django 4.1.7 on 2023-04-12 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0004_useraccount_panoraadhar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='acc_creation_dte',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='acc_creation_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 4, 12, 19, 27, 43, 904579), null=None),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='lastname',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
