# Generated by Django 4.1.7 on 2023-04-12 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0005_rename_fullname_useraccount_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='acc_creation_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 4, 12, 21, 5, 33, 837835), null=None),
        ),
    ]
