# Generated by Django 4.1.7 on 2023-04-16 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0007_useraccount_is_authenticated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='acc_creation_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 4, 16, 12, 58, 38, 733603), null=None),
        ),
    ]
