# Generated by Django 4.1.7 on 2023-04-17 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0009_alter_useraccount_acc_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='acc_creation_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 4, 17, 19, 58, 16, 752712), null=None),
        ),
    ]
