# Generated by Django 4.1.7 on 2023-04-26 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0011_usersalary_alter_useraccount_acc_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1024, unique=True)),
                ('message_id', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.CharField(default='', max_length=1024)),
                ('receiver', models.CharField(default='', max_length=1024)),
                ('category', models.CharField(default='', max_length=1024)),
                ('is_categorized', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='acc_creation_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 4, 26, 20, 43, 29, 109922), null=None),
        ),
    ]
