# Generated by Django 4.1.7 on 2023-04-26 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0012_user_messages_alter_useraccount_acc_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_messages',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='acc_creation_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 4, 26, 21, 58, 1, 666250), null=None),
        ),
    ]
