# Generated by Django 4.1.7 on 2023-04-26 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0014_alter_user_messages_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_messages',
            name='category',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='acc_creation_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 4, 26, 22, 11, 51, 724171), null=None),
        ),
    ]
