# Generated by Django 4.1.7 on 2023-04-26 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0016_alter_user_messages_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='acc_creation_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 4, 26, 22, 17, 27, 323774), null=None),
        ),
    ]
