# Generated by Django 4.1.7 on 2023-05-01 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finplan360', '0020_usernetsavings_update_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_message_deletecheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1024)),
                ('message_delete_check', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='acc_creation_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 5, 1, 16, 16, 38, 16288), null=None),
        ),
    ]
